### ISSUE TITLE
email backend: oauth

### ISSUE THREAD

**Issue by marcinwrochna** [sebastianjaszczur/aplikacjawww#19]
Aplikacja potrzebuje wysyłać maile.
Normalny sposób nie zadziała, bo nie za bardzo da się poprawnie skonfigurować domeny (rekordy MX) z openshiftem (którego ip jest zmienne). Zresztą i tak normalnym sposobem niemało maili trafia do spamu, szczególnie ponoć z serwerów Amazon EC2, na których openshift stoi.

Dlatego trzeba wysyłać maile inaczej. W starej aplikacji jest tak: właściciel warsztatywww@gmail.com klika coś w aplikacji i uprawnia dzięki OAuth aplikację do wysyłania maili przez SMTP gmaila. Niestety nie widzę implementacji takiego EmailBackend w Django (no kurdeee).
W poprzedniej aplikacji implementacja jest tu:
https://code.google.com/p/www-app/source/browse/email.php

Trzeba gdzieś w bazie zapisać access token, więc dodałbym model Settings z polami key: napis, value: napis, tak jak w starej aplikacji. Potem można tego używać do innych ustawień, których nie chcemy hardkodować (typu deadliny).

Także o ile nie ma lepszych pomysłów lub chętnych do implementacji to zająłbym się tym teraz.

**Comment by sebastianjaszczur** [comment]
Robiłem coś takiego już w Django, chociaż to było w celu - żeby wysyłało e-maile do adminów, jak komuś wyskoczy pięćsetka czy coś (BTW, też przydatne, aż dodam).

A implementacja tego jest domyślnie w Django, o tu można zobaczyć: https://docs.djangoproject.com/en/1.7/topics/email/

I w settings.py definiowałem tylko adres i hasło do konta na Gmailu. Co prawda, trzeba wtedy zapisać hasło, a nie access token - czy to bardzo boli?
No i dalej są funkcje domyślne (jak widać w linku wyżej).

Czy chodzi o coś innego, w stylu - interfejs do wysyłania e-maili itp?

**Comment by marcinwrochna** [comment]
No właśnie wpisywanie hasła trochę boli. Access token można zrevokować i zrobić nowy jednym kliknięciem, jak się już to napisze, i sprawdza skąd idzie żądanie. No ale ok, może być po prostu hasło. Tylko gdzie je zapisać? Jeśli w pliku to od razu do .gitignore i nie wiem jak to wrzucić dobrze na openshifta. Jeśli w bazie to każdy Staff będzie mógł czytać. Może da się jako environment variable w openshift?

**Comment by marcinwrochna** [comment]
rhc set-env VARIABLE1=VALUE1 VARIABLE2=VALUE2 -a myapp

To chyba tak by było najlepiej przechować hasło?

**Comment by sebastianjaszczur** [comment]
Tak, tak będzie najlepiej.

**Comment by sebastianjaszczur** [comment]
Czy masz dostęp do konta z którego chcielibyśmy wysyłać e-maile? Musiałbyś mi w jakiś sposób przekazać hasło też.
Zrobię zmiany w kodzie, dużo tego nie ma.

**Comment by marcinwrochna** [comment]
Hasła nie mam, nie wiem kto ma.. W starej aplikacji używałem własnego konta, ale hasła do niego nie dam :P
Jak zrobisz to dodaj proszę mwrochna+django@gmail.com do settings.py: ADMINS i MANAGERS.

**Comment by sebastianjaszczur** [comment]
Właśnie miałem spytać, czy Ciebie też dodać.
Z mailem jeszcze chwilę pomyślę.

**Comment by sebastianjaszczur** [comment]
Zrobiłem, możesz spojrzeć: https://github.com/sebastianjaszczur/aplikacjawww/commit/b04340857d6655acf7ad7d220303c7003cfa476f
Czekam jeszcze na hasło do warsztatywww@gmail.com

Coś jeszcze chcemy?

**Comment by marcinwrochna** [comment]
Super, to issue można po przetestowaniu zamknąć. Z podobnych rzeczy to
jeszcze fajnie by było skonfigurować logi, żeby przynajmniej się zapisywały.

2015-04-05 23:54 GMT+02:00 Sebastian Jaszczur <notifications@github.com>:

**Comment by marcinwrochna** [comment]
A, chyba trzeba dodać BrokenLinkEmailsMiddleware (to w praktyce jest dużo
spamu głównie od różnych botów szukających zbugowanego wordpressa, ale
łatwo to sobie odfiltrować).

2015-04-06 0:01 GMT+02:00 Marcin Wrochna <mwrochna@gmail.com>:

**Comment by marcinwrochna** [comment]
ON_PASS powinno być ON_PAAS (settings.py line 50)

2015-04-06 0:05 GMT+02:00 Marcin Wrochna <mwrochna@gmail.com>:

**Comment by sebastianjaszczur** [comment]
No nie wierzę w ten błąd. Dzięki.

**Comment by sebastianjaszczur** [comment]
Działa, dostałem wiadomość o błędzie. Na razie ustawiłem swoją skrzynkę pocztową - potem zmienię na warsztatywww@gmail.com, ale na razie miałem problemy z hasłami itp. Zamknę, jak to będzie.

**Comment by sebastianjaszczur** [comment]
No i działa już na warsztatywww@gmail.com
