### ISSUE TITLE
rejestracja bez fb

### ISSUE THREAD

**Issue by marcinwrochna** [sebastianjaszczur/aplikacjawww#2]
Możliwość rejestracji użytkownika bez posiadania konta na fb.
Opcja minimum: z kontem Google. 
Generalnie opcja zwykłej rejestracji powinna być.

**Comment by sebastianjaszczur** [comment]
Więc już jest rejestracja z kontem Google (i z Facebookiem wciąż).
Czy istnieją ludzie, którzy protestowaliby przeciwko logowaniu się i przez Google i przez FB? Bo myślałem, że można dodać GitHub'a - chyba nikt nie podejrzewa GH o szpiegowanie czy coś.

Zamykać issue, czy warto dodawać GitHuba (albo coś innego)? Bo jeśli nie trzeba - to nie warto zaśmiecać listy z możliwymi drogami logowania.

**Comment by sebastianjaszczur** [comment]
Inna kwestia - jak witryny udostępniają kilka możliwych opcji logowania to ja osobiście często się mylę i loguje się raz z FB, raz z G+. Jeśli to jest popularny problem to:
1) mielibyśmy dużo userów w dwóch "kopiach"
2) userzy logowaliby się na zły, mówili sobie "crap, nie to konto" i się wylogowywali i logowali znowu.

Widzi ktoś jakieś rozwiązanie? Np. żebyśmy pisali, że FB (albo G+) jest "preferowany". A może coś innego?

**Comment by marcinwrochna** [comment]
Jak ktoś np. logował się na fb i teraz loguje się G+, to można wykrywać imięnazwisko lub maila, zaproponować zalogowanie jako istniejący profil fb i autentykować fb, ewentualnie autentykować też G+ i dodać wtedy wpis, żeby od tej pory oba będą logowały na tego samego Usera.

Trochę zachodu, no ale rzeczywiście warto.
GitHuba chyba nie warto, bo 1. nie każdy ma tam nazwę='first_name last_name', 2. to nadal jest amerykański portal, więc śledzenie jakieś na pewno jest :p 
Spróbuję dodać UW-owe USOSa API (OAuth 1).

Także zająłbym się teraz tą duplikacją, a potem ewentualnie spróbował dodać ręczną rejestrację, bo niektórzy jednak tak lubią (bo np. nie mają ani G+ ani fb ani nic popularnego).

**Comment by sebastianjaszczur** [comment]
OK, dzięki. Czy możesz dodać się jako "assignee"? Ja szczerze mówiąc nie wiem jak to działa/jak powinno działać.

Co do "Spróbuję dodać UW-owe USOSa API (OAuth 1).":
Czy na pewno warto? W życiu o tym nie słyszałem, więc przypuszczam że mały promil użytkowników może tego użyć. Pracy pewnie mało, żeby to dodać, ale zaśmieca się ekran, a wartość mała. Chyba, że to jest jakieś popularne, a ja nie słyszałem?

**Comment by marcinwrochna** [comment]
Jedyny sposób, żebym mógł się dodać lub tagować, to dodać mnie do Collaborators co mi daje uprawnienia do pusha (swoją drogą, jest organizacja WWW na GitHubie i 'organizacje' mogą trochę więcej, ale nadal mogą uprawniać tylko albo do read-only albo z grubsza pełen dostęp z pushem włącznie).

Większość studentów ma konto na USOSie swojej uczelni i okazuje się, że (względnie świeże wersje) obsługują api z autentykacją przez OAuth1, więc można je po prostu wpisać jako providerów. Ale żeby obsłużyć nie tylko Uniwersytet Warszawski to by trzeba dać przycisk z wyborem uczelni - pomyślę później czy warto.

**Comment by sebastianjaszczur** [comment]
Działa, więc zamykam - jeśli usłyszę krzyki, że brakuje jeszcze jakiś metod logowania, to się otworzy na nowo.
