### ISSUE TITLE
Lista warsztatów

### ISSUE THREAD

**Issue by Ramlak** [sebastianjaszczur/aplikacjawww#21]
Potrzebna jest lista warsztatów dla organizatorów, żeby oceniać i potem kwalifikować warsztaty.

**Comment by sebastianjaszczur** [comment]
Robię.

**Comment by sebastianjaszczur** [comment]
I zrobiona lista warsztatów, choć w trywialny sposób. Trzeba jeszcze poprawić jej funkcjonalności - znacząco. Jednak to przenoszę do innego issue.
