### ISSUE TITLE
Wygląd strony

### ISSUE THREAD

**Issue by Ramlak** [sebastianjaszczur/aplikacjawww#22]
Wygląd profilu na razie jest dosyć biedny. Trzeba by tam ogarnąć cssa.

**Comment by sebastianjaszczur** [comment]
Profil moim zdaniem jest teraz bardzo ładny - można zmienić w podobny sposób ręsztę formów, i w przyszłości tak samo używać tego schematu (bootstrapowego, zintegrowanego z Django)
