### ISSUE TITLE
Funkcjonalność i wygląd listy warsztatów

### ISSUE THREAD

**Issue by sebastianjaszczur** [sebastianjaszczur/aplikacjawww#26]
Mamy dwa rodzaje listy warsztatów: lista wszystkich i lista konkretnego użytkownika (do jego wglądu).
Trzeba przemyśleć co powinny zawierać, w jakim celu istnieć i jak wyglądać. No i - zrobić.

**Comment by Ramlak** [comment]
Ok. Nie wiem czy akurat w formie tabeli ale uważam że lista wszystkich warsztatów powinna zawierać następujące informacje: osoba zgłaszająca, timestamp, kategorie, rodzaj.
Opcjonalnie: czy dodane zadania kwalifikacyjne itp -> to raczej w innymi issue dot. rekrutacji pewnie

Uważam też, że fajnie jakby można było to filtrować na bieżąco (np żeby pokazało tylko warsztaty Jaszczura, albo tylko z matematyki, albo tylko bloki warsztatowe itp) bez przeładowywania strony najlepiej.

Co do listy konkretnego użytkownika to na pewno jakieś rzeczy pomocne w rekrutacji ale to chyba nie teraz.

**Comment by Ramlak** [comment]
Wygląd: na pewno trzeba trochę poprawić. 
W moim odczuciu zbootstrapowana tabela powinna być wystarczająca.

**Comment by sebastianjaszczur** [comment]
Wygląda nieźle.
