### ISSUE TITLE
formularz proponowania warsztatów

### ISSUE THREAD

**Issue by marcinwrochna** [sebastianjaszczur/aplikacjawww#3]
- widok Twoje Warsztaty na listę z przejściem do dodania i edycji istniejących
- model Warsztatów (tytuł, prowadzący, opis, rodzaj=blok/luźny, czas trwania [x1,5h], dział=podzbiór {mat,fiz,...})
- formularz Dodaj/Edytuj Warsztaty

(Ewentualne bajery: możliwość dodawania współprowadzących.)

**Comment by sebastianjaszczur** [comment]
Nie ma czasu trwania - wydaje mi się, że wszystkie warsztaty i tak będą takie same czasowo, więc nie ma co wybierać.
