### ISSUE TITLE
Feature request: edycja w Markdown

### ISSUE THREAD

**Issue by stared** [sebastianjaszczur/aplikacjawww#30]
Edycja w czystym HTMLu ma tę wadę, że styl różnych wpisów będzie inny, z powodu zamierzonych i niezamierzonych zmian. Czy wchodzi w grę zrobienie edycji opisów w Markdown? 

Widziałem taki edytor: https://tibastral.github.io/markdownify/ (ten jest bez wzorów, ale może można łatwo podłączyć do tego MathJaXa).

**Comment by Ramlak** [comment]
CKEditor daje chyba sporo więcej możliwości. Po za tym przy markdownie też nie jest oczywiste że ludzie będą się trzymać schematu. 

Może lepszym pomysłem będzie ustawienie szablonów w CKEditorze?

**Comment by stared** [comment]
Wiesz, przy Markdownie schematu trzeba się trzymać, bo np. nie ma możliwości zmiany kroju czy koloru czcionki.
Niezależnie - szablony się przydadzą.

**Comment by sebastianjaszczur** [comment]
Szczerze, nie widzę zbyt dużo korzyści w używaniu Markdown. Prawda, schemat jest wymuszany - ale też w CKEditor mamy wybór - możemy dać swobodę, możemy zasugerować wygląd szablonami (co myślę powinniśmy robić), a w ekstremalnym przypadku - ograniczyć możliwości i np. nie pozwalać na zmianę koloru, fontu, czegokolwiek innego.
Więc wydaje mi się, że możliwości są większe - i to przede wszystkim możliwości konfiguracji.

Ponadto wydaje mi się, że edytowanie w takim CKEditor jest i prostsze i wygodniejsze. Także bardziej intuicyjne - do Markdown potrzebujesz jakiejś pomocy z odpowiedziami "jak zrobić h1", "jak pogrubić tekst". To nie wydaje mi się specjalnie user-friendly.

Oczywiście, jeśli są jakieś przewagi których nie widzę, chętnie się z nimi zapoznam - ale próbowałem jakieś znaleźć.

(myślę także, że utrzymywanie dwóch sposobów edycji także mija się z celem)
