### ISSUE TITLE
zmniejszyć stopień przezroczystości w podmenu

### ISSUE THREAD

**Issue by sygi** [sebastianjaszczur/aplikacjawww#32]
Podmenu, które pojawia się po kliknięciu w warsztaty albo artykuły jest półprzezroczyste i to średnio u mnie wygląda, bo przejście z ciemnego tła menu na białe tło strony przecina napis na górze.

Niestety nie wrzucę screena, bo z jakiegoś powodu print-screen przestał działać :P

**Comment by sebastianjaszczur** [comment]
Widzę o co chodzi. Jakieś dokładniejsze sugestie jak to poprawić?
Myślę, że można całkowicie przeźroczystość usunąć - ale jeszcze zobaczę jak to będzie wyglądać w praktyce.

**Comment by sebastianjaszczur** [comment]
Działa (właściwie to już od dawna).
