### ISSUE TITLE
Podpis przy wrzucaniu na FB (i może inne strony)

### ISSUE THREAD

**Issue by stared** [sebastianjaszczur/aplikacjawww#36]
Podpis przy wrzucaniu na FB (i może inne strony) zawiera "by" i autor template'a, zamiast organizaotrów czy czegoś w tym stylu.

![screen shot 2015-05-05 at 10 05 09](https://cloud.githubusercontent.com/assets/1001610/7468931/54665530-f30e-11e4-9f14-0170e60fb5c0.png)

**Comment by sebastianjaszczur** [comment]
Hmm, dobra uwaga. Dziwne to dosyć, zobaczę.

**Comment by sebastianjaszczur** [comment]
Co wrzucić w takim razie jako autora? Na razie jest "Wakacyjne Warsztaty Wielodyscyplinarne". Ale jeśli ktoś ma lepszą propozycję to można zmienić.

**Comment by sebastianjaszczur** [comment]
Zrobione, ale facebook wolno aktualizuje, niestety.

**Comment by sebastianjaszczur** [comment]
Nawet facebook zaaktualizował. Jeśli ktoś ma lepszy pomysł na "autora" to dajcie tu znać.
