### ISSUE TITLE
Przebudowa profilu i obowiązek wypełnienia

### ISSUE THREAD

**Issue by Ramlak** [sebastianjaszczur/aplikacjawww#38]
Proponowałbym obowiązkowe wypełnienie danych w profilu dla zakwalifikowanych prowadzących i uczestników. Te dane mogą okazać się potem przydatne (szkoła do identyfikatorów np).

Po za tym opcja zaznaczenia "jestem wegetarianinem", specjalne wymogi żywieniowe i inne standardowe obozowe rubryczki.

Przy czym proponuję by nie było obowiązku wypełniania tego (szczególnie tych obozowych) do czasu kwalifikacji uczestników by nie odstraszyło to nowych ludzi natłokiem pracy potrzebnej do poruszania się po stronie.

**Comment by micha7a** [comment]
Jest realne żeby do niedzieli zrobić "standardowe obozowe rubryczki"? 
Są potrzebne np. do zamówienia koszulek (rozmiar + dla dziewczyn czy chcą damską czy męską). 
Poza tym trzeba uczestnikom i prowadzącym dać czas uzupełnienie tego.

**Comment by sebastianjaszczur** [comment]
Ehm, do niedzieli chcesz mieć rubryczki czy wypełnione rubryczki?
That said, jeśli zrobisz mi listę wszystkich rzeczy które tam mają być to
dam radę dziś wieczorem/jutro. Napisz listę tutaj, to ktoś będzie mógł
dodać ewentualnie.

**Comment by micha7a** [comment]
Chcę mieć rubryczki, żeby ludzie mogli zacząć je wypełniać ;)

To przepisując poprzedniej aplikacji:
1. Numer pesel:
2. Adres (do ubezpieczenia):
3. Pobyt: pole "od" i pole "do"
4. Miejsce zbiórki, do wyboru "we własnym zakresie", "Warszawa", "Kraków",
fajnie by było jakby admini mogli dodawać opcje ale to nie jest konieczne
5. Rozmiar koszulki: "XS","S","M","L","XL","XXL"
6. Miejsce na uwagi (z podpowiedzią "np. wegetarianin, uczulony na x")

A, powinno być wiadomo, że ktoś nie wypełnił. Czyli np nie robić opcji
standardowych, albo zrobić wszędzie opcję "nie wypełniłem i jest mi głupio"
:P

W dniu 21 lipca 2015 10:48 użytkownik Sebastian Jaszczur <
notifications@github.com> napisał:

> Ehm, do niedzieli chcesz mieć rubryczki czy wypełnione rubryczki?
> That said, jeśli zrobisz mi listę wszystkich rzeczy które tam mają być to
> dam radę dziś wieczorem/jutro. Napisz listę tutaj, to ktoś będzie mógł
> dodać ewentualnie.

**Comment by sebastianjaszczur** [comment]
Zrobione. Zalogować się -> profil -> informacje.
Musiałem przesunąć przycisk "Zapisz" na górę, bo na dole nie działał. Pytasz czemu? Ja też pytam.
Stawiam piwo śmiałkowi, który mi wytłumaczy czemu w pliku profile.html te linie:
```
<button class="btn btn-default big-button">Zapisz</button>
{% crispy user_info_page_form %}
```
Działają, a jak je zamienić kolejnością - to już zapisywanie nie będzie działać, bo przycisk w jakiś magiczny sposób znajdzie się poza formularzem. WTF?

**Comment by sebastianjaszczur** [comment]
A, niech ktoś potwierdzi, że działa, please.

**Comment by micha7a** [comment]
Jak dla mnie działa, dzięki :D

To teraz przydałoby się móc te informacje gdzieś wyświetlić ;) Ale to tak
za tydzień spokojnie wystarczy :P

A na pytanie czemu tak nie umiem oczywiście odpowiedzieć, ale mi się
podoba, że jest na górze ;)

W dniu 26 lipca 2015 03:59 użytkownik Sebastian Jaszczur <
notifications@github.com> napisał:

**Comment by Ramlak** [comment]
To mogę puszczać maila by wypełniali, czy czekamy?
Wydaje mi się że te obiadu nie będą robione z dokładnością do jednej
porcji,  ale podkreślam że "wydaje mi się".
Tak naprawdę ta rubryczka jest ważna dla prowadzących bo plan.
Kalmar
26 lip 2015 11:01 "micha7a" <notifications@github.com> napisał(a):

**Comment by micha7a** [comment]
Możesz wysyłać maila moim zdaniem :)
Ale to Ty tu rządzisz :P

Masz na grupie o czym jeszcze można napisać :P

W dniu 26 lipca 2015 12:04 użytkownik Ramlak <notifications@github.com>
napisał:

**Comment by micha7a** [comment]
Kochani, 
kiedy będzie można te informacje (wypełnione lub nie) zobaczyć? 
Bo są potrzebne do:
a) ułożenia planu zajęć
b) policzenia nieletnich
c) zamówienia koszulek 
Z każdą z tych rzeczy możemy sobie jakoś inaczej poradzić (z liczeniem nieletnich najgorzej), ale na przykład z koszulkami to nie wiem czy czekać czy zamawiać jakiekolwiek :P

**Comment by sebastianjaszczur** [comment]
To jest chyba zrobione. Jeśli nie to niech ktoś da znać. Dzięki.
