### ISSUE TITLE
rich text editor

### ISSUE THREAD

**Issue by marcinwrochna** [sebastianjaszczur/aplikacjawww#4]
Do m.in. pola opisu warsztatów.
Może być Markdown z previewem jak na githubie, ale chyba lepiej WYSIWYG np. TinyMCE.

Prędzej czy później będziemy chcieli w tych polach mieć latexa, więc warto spojrzeć czy jakaś opcja nie ma tego wbudowanego (przez MathJax, ew. przez wywoływanie latexa+imagemagick na serwerze). Ewentualnie bajer: załączniki.

**Comment by sebastianjaszczur** [comment]
Jest CKEditor - zamykam. Do załączników otwieram oddzielny issue.
