### ISSUE TITLE
wyłączyć paginację listy warsztatów

### ISSUE THREAD

**Issue by sygi** [sebastianjaszczur/aplikacjawww#42]
Obecnie strona z listą warsztatów zachowuje się tak:
- jak jest za dużo warsztatów, żeby je wyświetlić na jednej stronie, to wyświetla się na dole przełącznik: 1,2,3,4
- jak się kliknie na numerki, to się od razu zmieniają i wszystko jest fajnie
ALE:
jeśli przejdę na stronę 2, a potem kliknę na warsztaty, a potem zrobię <- w przeglądarce, to wracam na stronę 1, bo fakt bycia na stronie 2 nie jest nigdzie trzymany. Jest to zdecydowanie niewygodne.

Możliwe rozwiązania (zakładające, tak jak teraz, że strony 1,2,3,4 będą się szybko ładować):
- trzymanie numeru strony i ilości wierszy w ciasteczkach
- podzielenie listy na kilka stron (tzn. workshops/, workshops/2/, workshops/3/, etc) i ich cache'owanie. Na pewno to drugie da się zrobić za pomocą linijki w django, a podejrzewam, że pierwsze też.

**Comment by zielmicha** [comment]
Myślę, że najlepiej i najprościej byłoby wyłączyć paginację.

**Comment by marcinwrochna** [comment]
Też jestem za wyłączeniem paginacji, ja w każdym razie bym wolał żeby domyślnie było widać co najmniej 80. Jak patrzymy w google docsach to zawsze na wszystkie na raz i jakoś nie ma problemu.

**Comment by sygi** [comment]
Zgadzam się.
