### ISSUE TITLE
Dodać tracking wizyt

### ISSUE THREAD

**Issue by stared** [sebastianjaszczur/aplikacjawww#53]
Dodać tracking wizyt w Google Analytics (lub czymś innym). Przydatne do śledzenia z których kanałów przychodzą ludzie.

**Comment by sebastianjaszczur** [comment]
Wydaje mi się, że już są, tzn. kiedyś coś Marcin Wrochna dodawał - jego można pytać.

**Comment by marcinwrochna** [comment]
Zwykły google analytics jest prawie od początku, dawałem też Jaszczurowi
pełne admin prawa, więc powinno wystarczyć wejść na
https://www.google.com/analytics/web/? i pogrzebać (dodawanie innym
uprawnień też powinni działać).
Ewentualnie można pomyśleć o łączeniu tego z informacjami o zalogowanej
osobie i np. odfiltrować wejścia programistów, ale nigdy tego nie robiłem.
Źródła wejść powinny być i bez tego miarodajne.

**Comment by stared** [comment]
Jak jest to super. (A mogę dostać do wglądu? :))

Nie, nie chodziło mi o nic bardziej wyszukanego. (Nie warte świeczki.)
