### ISSUE TITLE
Komentarze przy ocenie

### ISSUE THREAD

**Issue by stared** [sebastianjaszczur/aplikacjawww#61]
Czasem prócz oceny za zadanie przydaje się komentarz (np. "Wyjątkowo niechlujnie" lub "Zrobił zadanie 3 genialnie"). Było w poprzedniej aplikacji WWW. Czy jest możliwość dodania takiego feature?

**Comment by sebastianjaszczur** [comment]
Dodane! Będę wdzięczny, jeśli ktoś potwierdzi, że działa, bo robiłem bardzo na przypał. "U mnie działa", ale nie wiem jak na produkcji.

**Comment by stared** [comment]
Dziękuję! U mnie działa.
