### ISSUE TITLE
Wersjonowanie warsztatów

### ISSUE THREAD

**Issue by zielmicha** [sebastianjaszczur/aplikacjawww#64]
Będziemy potrzebowali dodać pole do bazy/utworzyć archiwum na stare warsztaty. Są potrzebne do robienia archiwalnych programów.

**Comment by sebastianjaszczur** [comment]
To chyba oficjalnie działa, co nie? Tzn. "działa". Ale te niedziałające rzeczy to już tylko bugi, z którymi uporamy się oddzielnie.
