### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by kisieland** [sebastianjaszczur/aplikacjawww#65]
Odpalenie <pre>migrate.sh</pre> Bez istniejącej bazy danych skutkowało tym, ze django wyrzucał błąd postaci <pre>(Wstaw kilkanaście linijek tracebacku)
django.db.utils.OperationalError: no such table: wwwapp_article</pre> Wynikało to z tego, że django zamiast najpierw stworzyć bazę danych, ?interpretował wszystko? 
Rozwiązaniem było usunięcie większości kodu i pozostawienie niezbędnego minimum, odpalenie skryptu, wklejenie kodu i ponowne odpalenie skrytpu. 
Dawało to wtedy ładną bazę SQLite. 
Można ją dołączyć do kodu? 
Bodajże Miśka wspominała o problemach z postawieniem serwera.

**Comment by kam193** [comment]
Jeśli ktoś jeszcze ma problem z odpaleniem migracji, to u mnie wystarczyło:
1. w *wwwapp/urls.py* zakomentować wszystko od `from wwwapp` do końca;
2. zamiast tego umieścić (django chciało mieć jakikolwiek adres, żeby ruszyć):
    urlpatterns = patterns('',
        url(r'^admin/', include(admin.site.urls)))
3. Odpalić migrację. I działa.
