### ISSUE TITLE
o:graph data

### ISSUE THREAD

**Issue by stared** [sebastianjaszczur/aplikacjawww#66]
Obecnie opis i zdjęcie nie są zdefiniowane. Do sprawdzenia tu:

* https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fwarsztatywww.pl%2F

Obecnie na FB wygląda to tak:

![screen shot 2016-04-01 at 6 01 20 pm](https://cloud.githubusercontent.com/assets/1001610/14212564/d1f34c4e-f833-11e5-97e4-a148d176c635.png)

**Comment by sebastianjaszczur** [comment]
Zrobione.
