### ISSUE TITLE
Profil się nie tworzy dobrze

### ISSUE THREAD

**Issue by sebastianjaszczur** [sebastianjaszczur/aplikacjawww#70]
Wydaje mi się, że podczas tworzenia profilu przy pomocy FB nie tworzy się odpowiedni model UserInfo. Trzeba to załatać i zobaczyć ilu ludzi to dotyczy - pojedynczym użytkownikom można ten obiekt dodać ręcznie.

**Comment by sebastianjaszczur** [comment]
Załatałem w kodzie i naprawiłem źle stworzonych użytkowników.

**Comment by micha7a** [comment]
Czy to znaczy, że powinnam widzieć Nikolę w "info o ludziach"?

**Comment by sebastianjaszczur** [comment]
Hmm, nie. Info o ludziach się popsuło, bo wyświetla tylko zakwalifikowanych prowadzących, i zakwalifikowanych uczestników. Tylko prowadzących wyświetla z innego roku. To inny bug.

**Comment by sebastianjaszczur** [comment]
Zaraz dodam takie issue.
