### ISSUE TITLE
Zwykła strona o warsztatach nie działa

### ISSUE THREAD

**Issue by sebastianjaszczur** [sebastianjaszczur/aplikacjawww#71]
Chodzi o stronę /workshop/url-warsztatów a nie o /workshop/priv/url-warsztatow .
Prawdopodobnie ma to związek z niedawnym dodawaniem roku do modelu warsztatów.

**Comment by zielmicha** [comment]
Prawdopodobnie "this is not a bug, but a feature":
```
    if workshop.status != 'Z': # Zaakceptowane
        raise Http404("Warsztaty nie zostały zaakceptowane")
```

**Comment by sebastianjaszczur** [comment]
Dobra uwaga. Wydawało mi się, że wtedy powinien się wyświetlić komunikat "Warsztaty nie zostały zaakceptowane". Chyba, że pamięć mnie myli i nigdy taki komunikat się nie wyświetla. Nie wiem.

W każdym razie - trzeba by albo usunąć link albo dać możliwość wyświetlania strony.

Ale wydawało mi się, że w zeszłym roku pozwalaliśmy edytować te strony bez zaakceptowania (bo czemu nie?). I też je wyświetlać. Z drugiej strony to trochę security issue może być - dawać dostęp do edytora HTML niezaakceptowanym osobom, nawet jeśli mamy te whitelisty na tagi, a potem pozwalać taką stronę wyświetlać innym użytkownikom.

**Comment by sebastianjaszczur** [comment]
OK. Zgadzam się, it's not a bug, it's a feature.
W takim razie jednak trzeba by usunąć link do tej strony z /workshop/priv/url-warsztatow , co nie?

**Comment by sebastianjaszczur** [comment]
Teraz link wyświetla się tylko, jeśli warsztaty są zaakceptowane.
