### ISSUE TITLE
Filtrowanie e-maili po roku zgłoszenia

### ISSUE THREAD

**Issue by sebastianjaszczur** [sebastianjaszczur/aplikacjawww#77]

**Comment by Mrowqa** [comment]
Gotowe (commit d2c0b72).

**Comment by sebastianjaszczur** [comment]
Raczej zamykamy jak będzie wrzucone na produkcję i będzie można być pewnym, że działa itp. Wrzucę to dziś po południu.

**Comment by zielmicha** [comment]
Wrzucone i zdaje się działać po drobnym fixie.

**Comment by sebastianjaszczur** [comment]
"wszyscy uczestnicy o statusie odrzuconym" razem z "2015" - na dają żadnych rezultatów. Chyba tak nie powinno być? (Reszta wygląda na działającą.)

**Comment by sebastianjaszczur** [comment]
Zielmicha zwrócił uwagę, że użytkownicy zepsuli się dużo wcześniej. Strzelam, że przy jakiejś migracji, ale nie wiem.
W każdym razie - nikt z uczestników nie ma statusu "odrzucony" - każdy ma "zaakceptowany" lub None. W takim razie to jest oddzielna sprawa.
